### ISSUE TITLE
[thefarmersfront/nifi] QUESTION only: Are you the new maintainer of the cetic helm charts?

### ISSUE THREAD

**Issue by michaeltufar** [thefarmersfront/helm-nifi#38]
안녕 하세요!

Short question: Are you actively maintaining now this helm chart, as cetic stopped this? 

Background: I'm currently using the cetic helm chart, but would appreciate to use yours, as it supports up to NiFi 1.27.

Of course fine for me if you decided for a "one shot" fork and change for 1.27. I could download the chart and use locally then. 

But if you decided for being the new maintainer, my subsequent question is, if you plan (or maybe I've missed if already existing?) to provide your chart in public Helm repos, like cetic did with their Github pages on https://cetic.github.io/helm-charts 
I'm asking this, as it's sufficient for me is to use the repo chart directly, without the need to download it, in advance.

Thanks and regards,
Michael

**Comment by dp-daesung** [comment]
Hello, Michael.

Thank you for your interest in our repo. Currently, we are actively using version 1.27 and plan to continue maintenance for the time being. We also provide a public Helm repository, although the documentation has not yet been updated.

You can install it using the following commands:

- https://helloworld.kurly.com/helm-nifi/

```
helm repo add kurly https://helloworld.kurly.com/helm-nifi
helm install nifi kurly/nifi
```
Regards.

**Comment by michaeltufar** [comment]
THANKS a lot!!!
