### ISSUE TITLE
[thefarmersfront/nifi] Migration from cetic/nifi to kurly/nifi: Request entity too large: limit is 3145728

### ISSUE THREAD

**Issue by michaeltufar** [thefarmersfront/helm-nifi#39]
Hi,

while trying to use my cetic/nifi based helm script I'm unfortunately recognizing that with all options I've tested so far nothing works for me with your fork. 
Settings working fine with cetic/nifi leads to a
`Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728` with kurly/nifi

Confuses me, as the "helm template" leads to a yaml file ~80kB, much less than 3MB. Also setting max-request-bytes on K8s doesn't help.

Any hints?

**Comment by dp-daesung** [comment]
Hello,

I sincerely apologize for the inconvenience caused. Upon reviewing your request, we identified an issue with the deployed package. We have promptly addressed the matter by updating the .helmignore file to resolve this issue.

Thank you for bringing this to our attention! Please let us know if you encounter any further problems.
